//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ESantiagoExamenBarreraEntities : DbContext
    {
        public ESantiagoExamenBarreraEntities()
            : base("name=ESantiagoExamenBarreraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<Boleta> Boletas { get; set; }
        public virtual DbSet<Calificacione> Calificaciones { get; set; }
    
        public virtual ObjectResult<GetMateriasAsignadas_Result> GetMateriasAsignadas(Nullable<int> idAlumno)
        {
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("IdAlumno", idAlumno) :
                new ObjectParameter("IdAlumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMateriasAsignadas_Result>("GetMateriasAsignadas", idAlumnoParameter);
        }
    
        public virtual ObjectResult<GetMateriasNoAsignadas_Result> GetMateriasNoAsignadas(Nullable<int> idAlumno)
        {
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("IdAlumno", idAlumno) :
                new ObjectParameter("IdAlumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMateriasNoAsignadas_Result>("GetMateriasNoAsignadas", idAlumnoParameter);
        }
    
        public virtual int ProfesorMateriaDelete(Nullable<int> idProfesor, Nullable<int> idMateria)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            var idMateriaParameter = idMateria.HasValue ?
                new ObjectParameter("IdMateria", idMateria) :
                new ObjectParameter("IdMateria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProfesorMateriaDelete", idProfesorParameter, idMateriaParameter);
        }
    
        public virtual ObjectResult<ProfesorMateriaGetMateriasAsignadas_Result> ProfesorMateriaGetMateriasAsignadas(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProfesorMateriaGetMateriasAsignadas_Result>("ProfesorMateriaGetMateriasAsignadas", idProfesorParameter);
        }
    
        public virtual ObjectResult<ProfesorMateriaGetMateriasNoAsignadas_Result> ProfesorMateriaGetMateriasNoAsignadas(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProfesorMateriaGetMateriasNoAsignadas_Result>("ProfesorMateriaGetMateriasNoAsignadas", idProfesorParameter);
        }
    
        public virtual int ProfesorMateriaAdd(Nullable<int> idProfesor, Nullable<int> idMateria)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            var idMateriaParameter = idMateria.HasValue ?
                new ObjectParameter("IdMateria", idMateria) :
                new ObjectParameter("IdMateria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProfesorMateriaAdd", idProfesorParameter, idMateriaParameter);
        }
    
        public virtual int AlumnoMateriaAdd(Nullable<int> idAlumno, Nullable<int> idMateria)
        {
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("IdAlumno", idAlumno) :
                new ObjectParameter("IdAlumno", typeof(int));
    
            var idMateriaParameter = idMateria.HasValue ?
                new ObjectParameter("IdMateria", idMateria) :
                new ObjectParameter("IdMateria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AlumnoMateriaAdd", idAlumnoParameter, idMateriaParameter);
        }
    
        public virtual int AlumnoMateriaDelete(Nullable<int> idAlumno, Nullable<int> idMateria)
        {
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("IdAlumno", idAlumno) :
                new ObjectParameter("IdAlumno", typeof(int));
    
            var idMateriaParameter = idMateria.HasValue ?
                new ObjectParameter("IdMateria", idMateria) :
                new ObjectParameter("IdMateria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AlumnoMateriaDelete", idAlumnoParameter, idMateriaParameter);
        }
    
        public virtual ObjectResult<BoletaGetCalificaciones_Result> BoletaGetCalificaciones(Nullable<int> idAlumno)
        {
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("IdAlumno", idAlumno) :
                new ObjectParameter("IdAlumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BoletaGetCalificaciones_Result>("BoletaGetCalificaciones", idAlumnoParameter);
        }
    
        public virtual ObjectResult<BoletaGetMaterias_Result> BoletaGetMaterias(Nullable<int> numeroBoleta)
        {
            var numeroBoletaParameter = numeroBoleta.HasValue ?
                new ObjectParameter("NumeroBoleta", numeroBoleta) :
                new ObjectParameter("NumeroBoleta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BoletaGetMaterias_Result>("BoletaGetMaterias", numeroBoletaParameter);
        }
    
        public virtual int BoletaUpdateCalificacion(Nullable<decimal> calificacion, Nullable<int> idMateria, Nullable<int> numeroBoleta)
        {
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("Calificacion", calificacion) :
                new ObjectParameter("Calificacion", typeof(decimal));
    
            var idMateriaParameter = idMateria.HasValue ?
                new ObjectParameter("IdMateria", idMateria) :
                new ObjectParameter("IdMateria", typeof(int));
    
            var numeroBoletaParameter = numeroBoleta.HasValue ?
                new ObjectParameter("NumeroBoleta", numeroBoleta) :
                new ObjectParameter("NumeroBoleta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BoletaUpdateCalificacion", calificacionParameter, idMateriaParameter, numeroBoletaParameter);
        }
    }
}
